nasa/GeneLab_Data_Processing

Amplicon/454-and-IonTorrent/Workflow_Documentation/SW_Amp454IonTor/README.md
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A/README.md
Metagenomics/Estimate_host_reads_in_raw_data/Workflow_Documentation/SW_MGEstHostReads/README.md
Metagenomics/Illumina/Workflow_Documentation/SW_MGIllumina/README.md
Metagenomics/Remove_human_reads_from_raw_data/Workflow_Documentation/SW_MGRemoveHumanReads-A/README.md

the changes are the same for all 5

adding mamba to pages with instructions for installing genelab-utils

---

Amplicon/Illumina/Pipeline_GL-DPPD-7104_Versions/GL-DPPD-7104-A.md
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A/CHANGELOG.md
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A/workflow_code/Snakefile
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A/workflow_code/scripts/Illumina-PE-R-processing.R
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A/workflow_code/scripts/Illumina-SE-R-processing.R
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-A/workflow_code/scripts/slurm-status.py

- assay-specific suffixes added
- slurm parameters added to specific rules as needed for cluster limits actually being enforced
- slurm-status.py script added for checking/reporting status per rule when slurm is used
- fix where some ITS datasets would fail biome creation
- version bump in Snakefile to v1.1.1
- updated changelog
- updated protocol doc
- added versions to tools
- added assay-specific suffixes to output files

Updating amplicon workflow

---

Microarray/Affymetrix/Pipeline_GL-DPPD-7114_Versions/GL-DPPD-7114.md
RNAseq/Pipeline_GL-DPPD-7101_Versions/GL-DPPD-7101-F.md
Raw_Data_Generation/UPX_kit_for_bulk_RNAseq/Pipeline_GL-DPPD-7108_Versions/GL-DPPD-7108.md

Updated RNA-Seq pipeline document, other documents 
- Added multiqc .zip files, renamed outputs for multiqc steps
- GL-DPPD-7114.md: Fixed cex and updated dp_tools (from https://github.com/nasa/GeneLab_Data_Processing/pull/31)
- GL-DPPD-7108.md: Fixed typo in GL-DPPD-7108.md (from https://github.com/nasa/GeneLab_Data_Processing/pull/34)

Document updates

---

Metagenomics/Illumina/Pipeline_GL-DPPD-7107_Versions/GL-DPPD-7107.md
Metagenomics/Illumina/Workflow_Documentation/README.md
Metagenomics/Illumina/Workflow_Documentation/SW_MGIllumina/CHANGELOG.md
Metagenomics/Illumina/Workflow_Documentation/SW_MGIllumina/workflow_code/Snakefile
Metagenomics/Illumina/Workflow_Documentation/SW_MGIllumina/workflow_code/config.yaml
Metagenomics/Illumina/Workflow_Documentation/SW_MGIllumina/workflow_code/scripts/slurm-status.py

details in commits and the Illumina metagenomics workflow CHANGELOG.md

Merging metagenomics branch with updated metagenomics workflow v2.0.4

---

Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/README.md
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/workflow_code/scripts/run_workflow.py

- Add uniqueness check + nonletter primer check to run_workflow.py
- Stop 16S and ITS target arguments from matching "16S and ITS" assays

SW_AmpIllumina-B: run_workflow.py changes

---

RNAseq/Pipeline_GL-DPPD-7101_Versions/GL-DPPD-7101-F.md
RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/bin/combined_ercc_analysis.ipynb
RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/config/software/by_docker_image.config

Removed a whitespace in by_docker_image.config that was preventing identification of RUNSHEET_FROM_GLDS by Nextflow

NF_RCP: Remove whitespace in by_docker_image.config

---

Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/workflow_code/Snakefile
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/workflow_code/scripts/Illumina-PE-R-processing.R
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/workflow_code/scripts/Illumina-SE-R-processing.R
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/workflow_code/visualizations/Illumina-R-visualizations.R
Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/workflow_code/visualizations/README.md

- Change "GLAmpSeq" suffix to "_GLAmpSeq" for more flexible naming
- Change order of vis script parameters, update associated readme changes
- Remove quotation marks from manual visualization script run command
- Improve construction of plot directory paths and file names in visualization script

SW_AmpIllumina-B: Assay suffix changes

---

Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/CHANGELOG.md

Sync SW_AmpIllumina-B/CHANGELOG.md from dev branch
- Add info for new workflow_code/visualizations/ directory

Sync SW_AmpIllumina-B/CHANGELOG.md

---

Microarray/Affymetrix/Pipeline_GL-DPPD-7114_Versions/GL-DPPD-7114.md

DEV_NF_MAAffymetrix: DPPD typo fix

---

Amplicon/Illumina/Workflow_Documentation/SW_AmpIllumina-B/README.md

- Improved --target documentation to clarify that it is required
- Fixed example run command to include --target

SW_AmpIllumina-B: --target documentation changes

---

Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/CHANGELOG.md
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/README.md
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/bin/Agile1CMP.qmd
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/modules/AGILE1CH.nf
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/nextflow.config
Microarray/Agilent_1-channel/Workflow_Documentation/README.md

NF_MAAgilent1ch: Update workflow version from 1.0.2 to 1.0.3

---

Microarray/Affymetrix/Workflow_Documentation/NF_MAAffymetrix/CHANGELOG.md
Microarray/Affymetrix/Workflow_Documentation/NF_MAAffymetrix/README.md
Microarray/Affymetrix/Workflow_Documentation/NF_MAAffymetrix/workflow_code/bin/Affymetrix.qmd
Microarray/Affymetrix/Workflow_Documentation/NF_MAAffymetrix/workflow_code/modules/PROCESS_AFFYMETRIX.nf
Microarray/Affymetrix/Workflow_Documentation/NF_MAAffymetrix/workflow_code/nextflow.config
Microarray/Affymetrix/Workflow_Documentation/README.md

NF_MAAffymetrix: Update workflow version from 1.0.3 to 1.0.4

---

Methyl-Seq/Pipeline_GL-DPPD-7113_Versions/GL-DPPD-7113.md

- fix issue #94 (https://github.com/nasa/GeneLab_Data_Processing/issues/94) by passing unsorted raw Bismark alignment output to deduplication step
- updated versions of all tools to latest
- updated broken documentation links (updates to TrimGalore and Bismark included enhancements/new locations for tool documentation)

Updates for issue #94

---

Methyl-Seq/Pipeline_GL-DPPD-7113_Versions/GL-DPPD-7113.md

- added clipping parameters for random-priming library type
- added gzip parameter to bismark alignment command to reduce intermediate file size

Clipping and performance updates

---

Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/CHANGELOG.md
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/README.md
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/bin/Agile1CMP.qmd
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/bin/dp_tools__agilent_1_channel/config.yaml
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/main.nf
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/modules/GENERATE_SOFTWARE_TABLE/main.nf
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/modules/GENERATE_SOFTWARE_TABLE/resources/usr/bin/SoftwareYamlToMarkdownTable.py
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/modules/POST_PROCESSING/GENERATE_PROTOCOL/main.nf
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/modules/POST_PROCESSING/GENERATE_PROTOCOL/resources/usr/bin/generate_protocol.sh
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/nextflow.config
Microarray/Agilent_1-channel/Workflow_Documentation/NF_MAAgilent1ch/workflow_code/post_processing.nf
Microarray/Agilent_1-channel/Workflow_Documentation/README.md

Changes include:
- #85 
- #96
- #97
- #99
- #100

NF_MAAgilent1ch: Update workflow version from 1.0.3 to 1.0.4

---

GeneLab_Reference_Annotations/Workflow_Documentation/GL_RefAnnotTable-A/README.md
GeneLab_Reference_Annotations/Workflow_Documentation/GL_RefAnnotTable-A/workflow_code/bin/prepull_apptainer.sh
GeneLab_Reference_Annotations/Workflow_Documentation/GL_RefAnnotTable-A/workflow_code/bin/prepull_singularity.sh
GeneLab_Reference_Annotations/Workflow_Documentation/GL_RefAnnotTable-A/workflow_code/config/software/by_docker_image.config
GeneLab_Reference_Annotations/Workflow_Documentation/GL_RefAnnotTable-A/workflow_code/install-org-db.R

Reorganized workflow documentation:
- Update to focus on Singularity approach + local environment only.
- Remove Singularity installation commands, refer the user to Singularity documentation instead.
Bug Fix:
- Fixed issue in running the stand-alone org.db installation script.

[GL_RefAnnotTable] Fixes

---

Metagenomics/Illumina/Workflow_Documentation/NF_MGIllumina-A/README.md
Metagenomics/Illumina/Workflow_Documentation/NF_MGIllumina-A/workflow_code/main.nf
Metagenomics/Illumina/Workflow_Documentation/NF_MGIllumina-A/workflow_code/nextflow.config
Metagenomics/Illumina/Workflow_Documentation/NF_MGIllumina-A/workflow_code/slurm_submit.slurm
Metagenomics/Illumina/Workflow_Documentation/README.md

Edited the README to contain outputs of post-processing and changed --GLDS_accession to --accession.

Metagenomics Illumina Nextflow workflow: Edited README files and accession parameter

---

Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/bin/alpha_diversity.R
Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/bin/beta_diversity.R
Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/bin/pairwise_ancombc1.R
Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/bin/pairwise_ancombc2.R
Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/bin/plot_taxonomy.R
Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/bin/run_deseq2.R
Amplicon/Illumina/Workflow_Documentation/NF_AmpIllumina-B/workflow_code/main.nf

I made the following changes:
1. Deleted the use of here R package for file path prediction.
2. Added code to filter out organelle (Mitochondria and Chloroplast) assignments before running ANCOMBC.
3. Changed the data type for the rarefaction_depth parameter from [STRING] to [INTEGER].

Amplicon Illumina nextflow conversion: deleted here and added organelle filtering

---

RNAseq/Workflow_Documentation/NF_RCP/workflow_code/bin/update_assay_table.py
RNAseq/Workflow_Documentation/NF_RCP/workflow_code/bin/vv_dge_deseq2.py

- Undo assay table column changes / updates for the time being
- vv_dge update

undo pending assay table changes, add suspect log2fc table output

---

Metagenomics/Illumina/Pipeline_GL-DPPD-7107_Versions/GL-DPPD-7107-A.md
Metagenomics/Illumina/Workflow_Documentation/NF_MGIllumina/README.md

Pipeline doc
- fixed typo in sed command
NF workflow doc
- added explicit definitions for all Nextflow profiles available
- removed slurm from example commands
- updated section headings to adjust for slurm removal
- added conda_megahit parameter definition and referral to help command for other conda environment parameters

[DEV_Metagenomics_Illumina] Minor documentation updates

---

Amplicon/Illumina/Pipeline_GL-DPPD-7104_Versions/GL-DPPD-7104-C.md

NF-AmpIllumina pipeline document updates associated with https://github.com/nasa/GeneLab_AmpliconSeq_Workflow/pull/2

[NF-AmpIllumina] Pipeline document updates

---

Amplicon/Illumina/Pipeline_GL-DPPD-7104_Versions/GL-DPPD-7104-C.md

- Add software to pipeline document
- Fix typo
- Change curly quotes to straight quotes

[NF-AmpIllumina] Add software to pipeline doc

---

Amplicon/Illumina/Pipeline_GL-DPPD-7104_Versions/GL-DPPD-7104-C.md
Amplicon/Illumina/Workflow_Documentation/README.md

Minor AmpIllumina pipeline GL-DPPD-7104-C updates to sync with NF_AmpIllumina 1.0.3 
- Add zipped files
- Report rarefaction_depth used
- Add assay_suffix where needed
- sync alpha/beta diversity code

Update AmpIllumina GL-DPPD-7104-C pipeline doc
